FROM oven/bun:1
WORKDIR /app
COPY bun.lock .
COPY packages/server/package.json .
RUN bun install
COPY packages/server .
RUN bunx prisma generate
COPY docker/entrypoint.sh /entrypoint.sh
COPY docker/healthcheck.ts /healthcheck.ts
RUN chmod +x /entrypoint.sh
ENTRYPOINT  ["/entrypoint.sh"]
CMD [ "bun","index.ts" ]
